<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="2" ignored="2" total="10" passed="5" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-11-06T13:14:46 IST" name="Suite" finished-at="2024-11-06T13:15:45 IST" duration-ms="58345">
    <groups>
      <group name="ErrorValidation">
        <method signature="ErrorValidation.LoginError()[pri:0, instance:Frameworks.ErrorValidation@7a1a14a4]" name="LoginError" class="Frameworks.ErrorValidation"/>
      </group> <!-- ErrorValidation -->
    </groups>
    <test started-at="2024-11-06T13:14:46 IST" name="Test" finished-at="2024-11-06T13:15:22 IST" duration-ms="35485">
      <class name="Frameworks.POM">
        <test-method is-config="true" signature="Launching()[pri:0, instance:Frameworks.POM@ae3540e]" started-at="2024-11-06T13:14:47 IST" name="Launching" finished-at="2024-11-06T13:14:53 IST" duration-ms="6329" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Launching -->
        <test-method signature="OrderPlacement(java.util.HashMap)[pri:0, instance:Frameworks.POM@ae3540e]" started-at="2024-11-06T13:14:53 IST" name="OrderPlacement" data-provider="data" finished-at="2024-11-06T13:15:02 IST" duration-ms="9052" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Test@123, ProductName=IPHONE 13 PRO, email=ramesharavind96@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderPlacement -->
        <test-method is-config="true" signature="close()[pri:0, instance:Frameworks.POM@ae3540e]" started-at="2024-11-06T13:15:02 IST" name="close" finished-at="2024-11-06T13:15:02 IST" duration-ms="434" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method is-config="true" signature="Launching()[pri:0, instance:Frameworks.POM@ae3540e]" started-at="2024-11-06T13:15:02 IST" name="Launching" finished-at="2024-11-06T13:15:04 IST" duration-ms="1727" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Launching -->
        <test-method signature="OrderPlacement(java.util.HashMap)[pri:0, instance:Frameworks.POM@ae3540e]" started-at="2024-11-06T13:15:04 IST" name="OrderPlacement" data-provider="data" finished-at="2024-11-06T13:15:12 IST" duration-ms="7560" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Iamking@000, ProductName=ZARA COAT 3, email=shetty@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderPlacement -->
        <test-method is-config="true" signature="close()[pri:0, instance:Frameworks.POM@ae3540e]" started-at="2024-11-06T13:15:12 IST" name="close" finished-at="2024-11-06T13:15:12 IST" duration-ms="364" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method is-config="true" signature="Launching()[pri:0, instance:Frameworks.POM@ae3540e]" started-at="2024-11-06T13:15:12 IST" name="Launching" finished-at="2024-11-06T13:15:14 IST" duration-ms="1572" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Launching -->
        <test-method signature="OrderPage(java.util.HashMap)[pri:0, instance:Frameworks.POM@ae3540e]" started-at="2024-11-06T13:15:14 IST" name="OrderPage" data-provider="data" finished-at="2024-11-06T13:15:17 IST" depends-on-methods="Frameworks.POM.OrderPlacement" duration-ms="3458" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Test@123, ProductName=IPHONE 13 PRO, email=ramesharavind96@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderPage -->
        <test-method is-config="true" signature="close()[pri:0, instance:Frameworks.POM@ae3540e]" started-at="2024-11-06T13:15:17 IST" name="close" finished-at="2024-11-06T13:15:17 IST" duration-ms="372" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method is-config="true" signature="Launching()[pri:0, instance:Frameworks.POM@ae3540e]" started-at="2024-11-06T13:15:17 IST" name="Launching" finished-at="2024-11-06T13:15:19 IST" duration-ms="1707" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Launching -->
        <test-method signature="OrderPage(java.util.HashMap)[pri:0, instance:Frameworks.POM@ae3540e]" started-at="2024-11-06T13:15:19 IST" name="OrderPage" data-provider="data" finished-at="2024-11-06T13:15:21 IST" depends-on-methods="Frameworks.POM.OrderPlacement" duration-ms="2204" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Iamking@000, ProductName=ZARA COAT 3, email=shetty@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderPage -->
        <test-method is-config="true" signature="close()[pri:0, instance:Frameworks.POM@ae3540e]" started-at="2024-11-06T13:15:21 IST" name="close" finished-at="2024-11-06T13:15:22 IST" duration-ms="399" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- Frameworks.POM -->
    </test> <!-- Test -->
    <test started-at="2024-11-06T13:15:22 IST" name="ErrorMessageVerification" finished-at="2024-11-06T13:15:45 IST" duration-ms="22271">
      <class name="Frameworks.ErrorValidation">
        <test-method is-config="true" signature="Launching()[pri:0, instance:Frameworks.ErrorValidation@7a1a14a4]" started-at="2024-11-06T13:15:22 IST" name="Launching" finished-at="2024-11-06T13:15:24 IST" duration-ms="1771" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Launching -->
        <test-method retried="true" signature="LoginError()[pri:0, instance:Frameworks.ErrorValidation@7a1a14a4]" started-at="2024-11-06T13:15:24 IST" name="LoginError" finished-at="2024-11-06T13:15:26 IST" duration-ms="1978" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email  password.] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email  password.] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Frameworks.ErrorValidation.LoginError(ErrorValidation.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginError -->
        <test-method is-config="true" signature="close()[pri:0, instance:Frameworks.ErrorValidation@7a1a14a4]" started-at="2024-11-06T13:15:26 IST" name="close" finished-at="2024-11-06T13:15:27 IST" duration-ms="394" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method is-config="true" signature="Launching()[pri:0, instance:Frameworks.ErrorValidation@7a1a14a4]" started-at="2024-11-06T13:15:27 IST" name="Launching" finished-at="2024-11-06T13:15:28 IST" duration-ms="1742" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Launching -->
        <test-method retried="true" signature="LoginError()[pri:0, instance:Frameworks.ErrorValidation@7a1a14a4]" started-at="2024-11-06T13:15:28 IST" name="LoginError" finished-at="2024-11-06T13:15:30 IST" duration-ms="1949" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email  password.] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email  password.] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Frameworks.ErrorValidation.LoginError(ErrorValidation.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginError -->
        <test-method is-config="true" signature="close()[pri:0, instance:Frameworks.ErrorValidation@7a1a14a4]" started-at="2024-11-06T13:15:30 IST" name="close" finished-at="2024-11-06T13:15:31 IST" duration-ms="362" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method is-config="true" signature="Launching()[pri:0, instance:Frameworks.ErrorValidation@7a1a14a4]" started-at="2024-11-06T13:15:31 IST" name="Launching" finished-at="2024-11-06T13:15:32 IST" duration-ms="1683" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Launching -->
        <test-method signature="LoginError()[pri:0, instance:Frameworks.ErrorValidation@7a1a14a4]" started-at="2024-11-06T13:15:32 IST" name="LoginError" finished-at="2024-11-06T13:15:35 IST" duration-ms="2944" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email  password.] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email  password.] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Frameworks.ErrorValidation.LoginError(ErrorValidation.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginError -->
        <test-method is-config="true" signature="close()[pri:0, instance:Frameworks.ErrorValidation@7a1a14a4]" started-at="2024-11-06T13:15:36 IST" name="close" finished-at="2024-11-06T13:15:36 IST" duration-ms="564" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method is-config="true" signature="Launching()[pri:0, instance:Frameworks.ErrorValidation@7a1a14a4]" started-at="2024-11-06T13:15:36 IST" name="Launching" finished-at="2024-11-06T13:15:38 IST" duration-ms="1959" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Launching -->
        <test-method signature="ProductError()[pri:0, instance:Frameworks.ErrorValidation@7a1a14a4]" started-at="2024-11-06T13:15:38 IST" name="ProductError" finished-at="2024-11-06T13:15:44 IST" duration-ms="6039" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductError -->
        <test-method is-config="true" signature="close()[pri:0, instance:Frameworks.ErrorValidation@7a1a14a4]" started-at="2024-11-06T13:15:44 IST" name="close" finished-at="2024-11-06T13:15:45 IST" duration-ms="487" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- Frameworks.ErrorValidation -->
    </test> <!-- ErrorMessageVerification -->
  </suite> <!-- Suite -->
</testng-results>
